# Generated by Django 3.0.4 on 2020-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(blank=True, verbose_name='PIN Number'),
        ),
    ]
