# Generated by Django 3.0.4 on 2020-04-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200421_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(default=0, verbose_name='PIN Number'),
        ),
    ]
