# Generated by Django 3.0.4 on 2020-04-21 17:17

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_1959'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
    ]
