# Generated by Django 3.0.4 on 2020-03-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='subject',
            table='tbl_subjects',
        ),
    ]
