# Generated by Django 3.0.4 on 2020-03-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200331_0745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='tbl_subject',
        ),
    ]
