# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200326_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
