# Generated by Django 3.0.4 on 2020-04-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200326_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
