# Generated by Django 3.0.4 on 2020-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200408_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
