# Generated by Django 3.0.4 on 2020-04-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_pin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customers',
        ),
    ]
