# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200326_1448'),
        ('currency', '0002_auto_20200326_1217'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id_number',
        ),
        migrations.AddField(
            model_name='account',
            name='currency_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
