# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='CurrCode',
            field=models.IntegerField(),
        ),
    ]
