# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-26 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200326_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id_number',
        ),
    ]
