# Generated by Django 3.0.4 on 2020-04-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200326_1448'),
        ('transactions', '0002_transactions_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='customer',
        ),
        migrations.AddField(
            model_name='transactions',
            name='AccNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
