# Generated by Django 3.0.4 on 2020-04-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_balance'),
        ('transactions', '0003_auto_20200408_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='SendMoney',
        ),
        migrations.AlterModelTable(
            name='sendmoney',
            table='sendMoney',
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('AccNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'db_table': 'withdraw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('AccNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'db_table': 'deposit',
                'managed': True,
            },
        ),
    ]
