# Generated by Django 3.0.4 on 2020-04-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='trans_code',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
