# Generated by Django 3.0.4 on 2020-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200413_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=10)),
                ('tCode', models.IntegerField()),
            ],
            options={
                'db_table': 'transcType',
                'managed': True,
            },
        ),
    ]
