# Generated by Django 3.0.4 on 2020-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_t_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_transactions',
            old_name='amount',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='all_transactions',
            name='destAcc',
        ),
        migrations.RemoveField(
            model_name='all_transactions',
            name='sourceAcc',
        ),
        migrations.RemoveField(
            model_name='all_transactions',
            name='trans_type',
        ),
        migrations.AddField(
            model_name='all_transactions',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_transactions',
            name='debit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_transactions',
            name='service_charge',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_transactions',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
