# Generated by Django 3.0.4 on 2020-04-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200414_2004'),
        ('transactions', '0009_auto_20200415_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmoney',
            name='recipient_name',
        ),
        migrations.AlterField(
            model_name='all_transactions',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
