# Generated by Django 3.0.4 on 2020-04-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='mobile',
        ),
    ]
