# Generated by Django 3.0.4 on 2020-03-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='student',
            table='tbl_student',
        ),
    ]
